### ISSUE TITLE
Is adding 'ml_dataframe' to pubspec.yaml still necessary?

### ISSUE THREAD

**Issue by dariyooo** [gyrdym/ml_preprocessing#27]
I am currently trying out this package and in the perquisites it is stated:

> The library depends on DataFrame class from the repo. It's necessary to use it as a
> dependency in your project, because you need to pack data into DataFrame before doing preprocessing. An example with a part of pubspec.yaml: ...

However when I do not add ```ml_dataframe: ^0.0.11``` to ```pubspec.yaml``` I can still use the package and the ```ml_dataframe``` package is also available in my app.

**Comment by gyrdym** [comment]
@CaptainDario Thank you for your attention to the lib, I'll look at this and fix it if there is a mistake

**Comment by gyrdym** [comment]
@CaptainDario there is no error - it's better to have `ml_dataframe` as a dependency in your pubspec for more control, usage of `ml_dataframe` in your case is implicit - it is taken from `ml_preprocessing` dependencies.

**Comment by dariyooo** [comment]
okay, than this can be closed.
